import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

export interface FrameworkDetection {
  frameworks: string[];
  fluent: boolean;
}

export interface InitResult {
  created: string[];
  updated: string[];
  unchanged: string[];
}

const BEGIN = '<!-- a11y-skills:begin generated -->';
const END = '<!-- a11y-skills:end generated -->';

const POINTER =
  '> Accessibility: follow [A11Y.md](A11Y.md) when writing or reviewing UI code (managed by `@aidevme/a11y init`).';

/** Host context files that receive the pointer snippet — only when they already exist. */
const HOST_FILES = ['CLAUDE.md', '.cursorrules', 'AGENTS.md', '.github/copilot-instructions.md'];

function generatedBlock(detection: FrameworkDetection): string {
  const lines: string[] = [];
  lines.push(BEGIN);
  lines.push('');
  lines.push(
    '_Generated by `@aidevme/a11y init` — do not edit between the markers; re-run init to refresh. Content outside the markers is yours and is preserved._',
  );
  lines.push('');
  lines.push('## Compliance target');
  lines.push('');
  lines.push('- Profile: **standard** (WCAG 2.2 AA). Change via `profile` in `.a11yrc.json`.');
  lines.push('');
  lines.push('## Core rules (all UI code)');
  lines.push('');
  lines.push('- Use semantic HTML elements before reaching for ARIA; never use ARIA to fix what an element choice would solve (SC 4.1.2).');
  lines.push('- Every interactive element must be reachable and operable by keyboard alone (SC 2.1.1).');
  lines.push('- Never remove a focus indicator without providing a visible replacement (SC 2.4.7).');
  lines.push('- Every image needs alt text; decorative images need `alt=""` (SC 1.1.1).');
  lines.push('- Every form control needs a programmatically associated label (SC 3.3.2).');
  lines.push('- Maintain a logical heading hierarchy — no skipped levels (SC 1.3.1).');
  lines.push('- Non-interference floor — never violate, at any profile: no keyboard traps (SC 2.1.2), no auto-playing audio without a stop (SC 1.4.2), nothing flashing more than 3×/s (SC 2.3.1), no moving content that cannot be paused (SC 2.2.2).');
  if (detection.frameworks.includes('react')) {
    lines.push('');
    lines.push('## React');
    lines.push('');
    lines.push('- Do not attach `onClick` to non-interactive elements without a keyboard handler and a role — prefer `<button>` (SC 2.1.1).');
    lines.push('- Never use a positive `tabIndex`; it breaks the natural focus order (SC 2.4.3).');
    lines.push('- Use `htmlFor`/`id` (or nesting) to associate labels with inputs (SC 3.3.2).');
    lines.push('- Anchors are for navigation; use a button for actions (`react-anchor-is-valid`).');
    lines.push('- Spell ARIA attributes correctly — the linter validates them (`react-aria-props`).');
  }
  if (detection.fluent) {
    lines.push('');
    lines.push('## Fluent UI v9');
    lines.push('');
    lines.push('- Icon-only `<Button>` requires `aria-label` (`fluent-button-accessible-name`).');
    lines.push('- Never override `aria-modal` on `<Dialog>` — Fluent manages modal semantics (`fluent-dialog-aria-modal`).');
    lines.push('- Give `<Field>` a `label` prop; give `<Spinner>` a `label`; give `<Image>` an `alt` (`fluent-field-label`, `fluent-spinner-label`, `fluent-image-alt`).');
  }
  lines.push('');
  lines.push('Run `npx @aidevme/a11y audit` before committing UI changes; findings reference the rule ids above.');
  lines.push('');
  lines.push(END);
  return lines.join('\n');
}

function defaultConfig(detection: FrameworkDetection): string {
  const rulePacks = [
    ...(detection.frameworks.includes('react') ? ['react'] : []),
    ...(detection.fluent ? ['fluent-ui'] : []),
  ];
  return `${JSON.stringify({ rulePacks, profile: 'standard', wcagVersion: '2.2' }, null, 2)}\n`;
}

/**
 * Idempotent project wiring (DESIGN §2.3a, §4.2): creates or refreshes
 * A11Y.md (generated block between markers, user content preserved), writes
 * .a11yrc.json only if absent, and appends the pointer snippet to each host
 * context file that exists and lacks it. Running twice changes nothing.
 */
export async function runInit(
  projectRoot: string,
  detection: FrameworkDetection,
): Promise<InitResult> {
  const result: InitResult = { created: [], updated: [], unchanged: [] };

  // .a11yrc.json — never overwrite an existing config
  const rcPath = join(projectRoot, '.a11yrc.json');
  if (existsSync(rcPath)) {
    result.unchanged.push('.a11yrc.json');
  } else {
    writeFileSync(rcPath, defaultConfig(detection), 'utf8');
    result.created.push('.a11yrc.json');
  }

  // A11Y.md — regenerate only the marked block
  const a11yPath = join(projectRoot, 'A11Y.md');
  const block = generatedBlock(detection);
  if (!existsSync(a11yPath)) {
    writeFileSync(a11yPath, `# A11Y.md — Accessibility guidelines for this project\n\n${block}\n`, 'utf8');
    result.created.push('A11Y.md');
  } else {
    const current = readFileSync(a11yPath, 'utf8');
    let next: string;
    const beginIdx = current.indexOf(BEGIN);
    const endIdx = current.indexOf(END);
    if (beginIdx !== -1 && endIdx !== -1 && endIdx > beginIdx) {
      next = current.slice(0, beginIdx) + block + current.slice(endIdx + END.length);
    } else {
      next = `${current.trimEnd()}\n\n${block}\n`;
    }
    if (next === current) {
      result.unchanged.push('A11Y.md');
    } else {
      writeFileSync(a11yPath, next, 'utf8');
      result.updated.push('A11Y.md');
    }
  }

  // Host pointers — only in files that already exist, never duplicated
  for (const rel of HOST_FILES) {
    const hostPath = join(projectRoot, rel);
    if (!existsSync(hostPath)) continue;
    const content = readFileSync(hostPath, 'utf8');
    if (content.includes('A11Y.md')) {
      result.unchanged.push(rel);
    } else {
      writeFileSync(hostPath, `${content.trimEnd()}\n\n${POINTER}\n`, 'utf8');
      result.updated.push(rel);
    }
  }

  return result;
}
